### ISSUE TITLE
playlist_youtube.luac causes no change to VLC behaviour

### ISSUE THREAD

**Issue by PeterOdogwu** [vvasuki/vlc-addons#1]
I downloaded the luac file from inside the lua addons folder by clicking on save link as. 
 I've put the luac file in C:\Program Files\VideoLAN\VLC\lua\playlist
and tried it with this playlist (https://www.youtube.com/watch?v=KjY6ruVXoG4&list=PL9Rj3VyOvkMpC8ALebOwQ1ihfiqzmt_Vr but I tried with multiple playlists and videos so I don't think the problem is the playlists) but nothing changes and VLC still fails to play Youtube videos and playlists. and the module doesn't seem to show up in the list of modules (in case it's supposed to). VLC treats YT videos in the same way, by playing a brief image of the youtube video and then refusing to play it any further. There's also no change when I put the luac file in "C:\Users\[myusername]\AppData\vlcluaplaylist"

**Comment by vvasuki** [comment]
I can open the playlist just fine. You've not installed the luac file correctly, it seems. I don't have a windows machine so can't verify / help much there. Still, just to check: Can you list C:\Program Files\VideoLAN\VLC\lua\playlist ? And can you attach the luac file you've installed?

**Comment by PeterOdogwu** [comment]
I don't have that directory (I don't have a C:\Program Files directory). I have C:\Program Files\VideoLAN\VLC\lua\playlist, and the file I added in there during the installation is playlist_youtube.luac, which I've attached as a text file because github doesn't seem to accept .lua files.

[playlist_youtube.txt](https://github.com/vvasuki/vlc-addons/files/4022222/playlist_youtube.txt)

**Comment by vvasuki** [comment]
That's not a lua file! You've downloaded a html file and named it lua (perhaps misguided by a link I had formerly placed in the plugin description). Please download https://raw.githubusercontent.com/vvasuki/vlc-addons/master/lua-addons/playlist_youtube.luac, rename to **playlist_youtube.luac and** enjoy.

**Comment by PeterOdogwu** [comment]
My bad and that seems to resolve most of the problems and playlists but there are still some specific videos which don't load, and I'm not sure I understand why. Would you mind trying this one: https://www.youtube.com/watch?v=H8HwenJoUs4 ?

**Comment by vvasuki** [comment]
I've observed it too - don't know the cause.
