### ISSUE TITLE
Notice: Youtube.lua must be updated for playlist_youtube.luac to work

### ISSUE THREAD

**Issue by diVineProportion** [vvasuki/vlc-addons#2]
It will appear that this playlist plugin does nothing but that it because your youtube.lua needs to be updated. 

save in same folder
https://raw.githubusercontent.com/videolan/vlc/master/share/lua/playlist/youtube.lua

**Comment by vvasuki** [comment]
It's already there - https://github.com/vvasuki/vlc-addons/tree/master/lua-addons . 

Further, I changed the installation instructions at https://www.pling.com/p/1344170/ and at https://github.com/vvasuki/vlc-addons .

**Comment by diVineProportion** [comment]
What do you mean? I was on VLC 3.0.8 and when I checked for updates it said I was current. Your playlist parser would not work until I dropped that file in manually.
